version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_controle_territorios
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-controle_territorios}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-change_me}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend_controle_territorios
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL:-jdbc:mysql://mysqldb:3306/controle_territorios?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-change_me}
    depends_on:
      - mysqldb

  frontend:
    build: ./frontend
    container_name: frontend_controle_territorios
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: